/*
StarMade Native Library
Copyright(C) 2016 Schine, GmbH

This program is free software : you can redistribute it and / or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.If not, see <http://www.gnu.org/licenses/>.
*/

/* DO NOT EDIT THIS FILE - it is machine generated */
#ifdef __APPLE__
#include <JavaVM/jni.h>
#else
#include <jni.h>
#endif
/* Header for class org_schema_game_server_controller_world_factory_planet_FastNoiseSIMD */

#ifndef _Included_org_schema_game_server_controller_world_factory_planet_FastNoiseSIMD
#define _Included_org_schema_game_server_controller_world_factory_planet_FastNoiseSIMD
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_schema_game_server_controller_world_factory_planet_FastNoiseSIMD
 * Method:    NewFastNoiseSIMD
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_org_schema_game_server_controller_world_factory_planet_FastNoiseSIMD_NewFastNoiseSIMD
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_schema_game_server_controller_world_factory_planet_FastNoiseSIMD
 * Method:    GetSIMDLevel
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_schema_game_server_controller_world_factory_planet_FastNoiseSIMD_GetSIMDLevel
  (JNIEnv *, jclass);

/*
 * Class:     org_schema_game_server_controller_world_factory_planet_FastNoiseSIMD
 * Method:    SetSIMDLevel
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_schema_game_server_controller_world_factory_planet_FastNoiseSIMD_SetSIMDLevel
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_schema_game_server_controller_world_factory_planet_FastNoiseSIMD
 * Method:    NativeFree
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_schema_game_server_controller_world_factory_planet_FastNoiseSIMD_NativeFree
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_schema_game_server_controller_world_factory_planet_FastNoiseSIMD
 * Method:    NativeSetSeed
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_schema_game_server_controller_world_factory_planet_FastNoiseSIMD_NativeSetSeed
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_schema_game_server_controller_world_factory_planet_FastNoiseSIMD
 * Method:    NativeGetSeed
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_schema_game_server_controller_world_factory_planet_FastNoiseSIMD_NativeGetSeed
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_schema_game_server_controller_world_factory_planet_FastNoiseSIMD
 * Method:    NativeSetFrequency
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_schema_game_server_controller_world_factory_planet_FastNoiseSIMD_NativeSetFrequency
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_schema_game_server_controller_world_factory_planet_FastNoiseSIMD
 * Method:    NativeSetNoiseType
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_schema_game_server_controller_world_factory_planet_FastNoiseSIMD_NativeSetNoiseType
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_schema_game_server_controller_world_factory_planet_FastNoiseSIMD
 * Method:    NativeSetAxisScales
 * Signature: (JFFF)V
 */
JNIEXPORT void JNICALL Java_org_schema_game_server_controller_world_factory_planet_FastNoiseSIMD_NativeSetAxisScales
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat);

/*
 * Class:     org_schema_game_server_controller_world_factory_planet_FastNoiseSIMD
 * Method:    NativeSetFractalOctaves
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_schema_game_server_controller_world_factory_planet_FastNoiseSIMD_NativeSetFractalOctaves
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_schema_game_server_controller_world_factory_planet_FastNoiseSIMD
 * Method:    NativeSetFractalLacunarity
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_schema_game_server_controller_world_factory_planet_FastNoiseSIMD_NativeSetFractalLacunarity
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_schema_game_server_controller_world_factory_planet_FastNoiseSIMD
 * Method:    NativeSetFractalGain
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_schema_game_server_controller_world_factory_planet_FastNoiseSIMD_NativeSetFractalGain
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_schema_game_server_controller_world_factory_planet_FastNoiseSIMD
 * Method:    NativeSetFractalType
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_schema_game_server_controller_world_factory_planet_FastNoiseSIMD_NativeSetFractalType
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_schema_game_server_controller_world_factory_planet_FastNoiseSIMD
 * Method:    NativeSetCellularReturnType
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_schema_game_server_controller_world_factory_planet_FastNoiseSIMD_NativeSetCellularReturnType
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_schema_game_server_controller_world_factory_planet_FastNoiseSIMD
 * Method:    NativeSetCellularDistanceFunction
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_schema_game_server_controller_world_factory_planet_FastNoiseSIMD_NativeSetCellularDistanceFunction
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_schema_game_server_controller_world_factory_planet_FastNoiseSIMD
 * Method:    NativeFillNoiseSet
 * Signature: (J[FIIIIII)V
 */
JNIEXPORT void JNICALL Java_org_schema_game_server_controller_world_factory_planet_FastNoiseSIMD_NativeFillNoiseSet
  (JNIEnv *, jclass, jlong, jfloatArray, jint, jint, jint, jint, jint, jint);

/*
 * Class:     org_schema_game_server_controller_world_factory_planet_FastNoiseSIMD
 * Method:    NativeFillSampledNoiseSet
 * Signature: (J[FIIIIIII)V
 */
JNIEXPORT void JNICALL Java_org_schema_game_server_controller_world_factory_planet_FastNoiseSIMD_NativeFillSampledNoiseSet
  (JNIEnv *, jclass, jlong, jfloatArray, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     org_schema_game_server_controller_world_factory_planet_FastNoiseSIMD
 * Method:    NativeFillNoiseSetVector
 * Signature: (J[FJFFF)V
 */
JNIEXPORT void JNICALL Java_org_schema_game_server_controller_world_factory_planet_FastNoiseSIMD_NativeFillNoiseSetVector
  (JNIEnv *, jclass, jlong, jfloatArray, jlong, jfloat, jfloat, jfloat);

/*
 * Class:     org_schema_game_server_controller_world_factory_planet_FastNoiseSIMD
 * Method:    NativeFillSampledNoiseSetVector
 * Signature: (J[FJIIIFFF)V
 */
JNIEXPORT void JNICALL Java_org_schema_game_server_controller_world_factory_planet_FastNoiseSIMD_NativeFillSampledNoiseSetVector
  (JNIEnv *, jclass, jlong, jfloatArray, jlong, jint, jint, jint, jfloat, jfloat, jfloat);

/*
 * Class:     org_schema_game_server_controller_world_factory_planet_FastNoiseSIMD
 * Method:    NewVectorSet
 * Signature: (I[F)J
 */
JNIEXPORT jlong JNICALL Java_org_schema_game_server_controller_world_factory_planet_FastNoiseSIMD_NewVectorSet
  (JNIEnv *, jclass, jint, jfloatArray);

/*
 * Class:     org_schema_game_server_controller_world_factory_planet_FastNoiseSIMD
 * Method:    FreeVectorSet
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_schema_game_server_controller_world_factory_planet_FastNoiseSIMD_FreeVectorSet
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_schema_game_server_controller_world_factory_planet_FastNoiseSIMD_CellularDistanceFunction */

#ifndef _Included_org_schema_game_server_controller_world_factory_planet_FastNoiseSIMD_CellularDistanceFunction
#define _Included_org_schema_game_server_controller_world_factory_planet_FastNoiseSIMD_CellularDistanceFunction
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_schema_game_server_controller_world_factory_planet_FastNoiseSIMD_CellularReturnType */

#ifndef _Included_org_schema_game_server_controller_world_factory_planet_FastNoiseSIMD_CellularReturnType
#define _Included_org_schema_game_server_controller_world_factory_planet_FastNoiseSIMD_CellularReturnType
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_schema_game_server_controller_world_factory_planet_FastNoiseSIMD_FractalType */

#ifndef _Included_org_schema_game_server_controller_world_factory_planet_FastNoiseSIMD_FractalType
#define _Included_org_schema_game_server_controller_world_factory_planet_FastNoiseSIMD_FractalType
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_schema_game_server_controller_world_factory_planet_FastNoiseSIMD_NoiseType */

#ifndef _Included_org_schema_game_server_controller_world_factory_planet_FastNoiseSIMD_NoiseType
#define _Included_org_schema_game_server_controller_world_factory_planet_FastNoiseSIMD_NoiseType
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
